"""add user_id to recordings

Revision ID: 13fb102037a2
Revises:
Create Date: 2026-07-11 15:32:01.856097

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "13fb102037a2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recordings", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "recordings", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "recordings", type_="foreignkey")
    op.drop_column("recordings", "user_id")
    # ### end Alembic commands ###
