"""add recordings user created index

Revision ID: 653a809f99e2
Revises: 9dd00b81763e
Create Date: 2026-07-31 08:56:49.569689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653a809f99e2'
down_revision: Union[str, Sequence[str], None] = '9dd00b81763e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_recordings_user_created', 'recordings', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recordings_user_created', table_name='recordings')
    # ### end Alembic commands ###
