"""added emailfield in users table

Revision ID: 9dd00b81763e
Revises: 13fb102037a2
Create Date: 2026-07-12 23:25:13.595213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9dd00b81763e"
down_revision: Union[str, Sequence[str], None] = "13fb102037a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=True))
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "email")
    # ### end Alembic commands ###
