"""add first_name, last_name in User model

Revision ID: baf74e5808dd
Revises: b5832e4a6be4
Create Date: 2026-08-13 07:20:36.595429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baf74e5808dd'
down_revision: Union[str, Sequence[str], None] = 'b5832e4a6be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_user_created'), table_name='generations')
    op.drop_table('generations')
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.create_table('generations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('audio_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('script', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('generations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('generations_pkey'))
    )
    op.create_index(op.f('ix_generation_user_created'), 'generations', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
